function cent = conv_mom_1_4(m1,m2,m3,m4)
%CONV_MOM_1_4
%    CENT = CONV_MOM_1_4(M1,M2,M3,M4)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Apr-2017 08:28:30

t2 = m1.^2;
cent = [0.0;m2-t2;m3-m1.*m2.*3.0+m1.*t2.*2.0;m4-m1.*m3.*4.0+m2.*t2.*6.0-t2.^2.*3.0];
