function [A,B] = tmmmp(w0_1,w0_2,w0_3,w0_4,w1_1_1,w1_2_1,w1_3_1,w1_4_1,w1_1_2,w1_2_2,w1_3_2,w1_4_2)
%TMMMP
%    [A,B] = TMMMP(W0_1,W0_2,W0_3,W0_4,W1_1_1,W1_2_1,W1_3_1,W1_4_1,W1_1_2,W1_2_2,W1_3_2,W1_4_2)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    08-Apr-2017 11:42:15

A = reshape([w1_1_1-w1_2_1,w1_3_1-w1_4_1,w1_1_2-w1_2_2,w1_3_2-w1_4_2],[2,2]);
if nargout > 1
    B = [w0_1-w0_2;w0_3-w0_4];
end
